In [1]:
! git clone https://github.com/ds4e/scratchpad
%run ./scratchpad/get_data.py

Cloning into 'scratchpad'...
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 118 (delta 42), reused 31 (delta 30), pack-reused 65 (from 2)
Receiving objects: 100% (118/118), 1.76 MiB | 8.32 MiB/s, done.
Resolving deltas: 100% (55/55), done.
Downloading course data...
Download complete
Extracting data files...
Data extracted

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


df = pd.read_csv('./data/brazil_default.csv', encoding='latin1')

/tmp/ipykernel_602/3697957170.py:7: DtypeWarning: Columns (51,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./data/brazil_default.csv', encoding='latin1')

In [5]:
df.columns.to_list()

['ID_CLIENT',
 'CLERK_TYPE',
 'PAYMENT_DAY',
 'APPLICATION_SUBMISSION_TYPE',
 'QUANT_ADDITIONAL_CARDS',
 'POSTAL_ADDRESS_TYPE',
 'SEX',
 'MARITAL_STATUS',
 'QUANT_DEPENDANTS',
 'EDUCATION_LEVEL',
 'STATE_OF_BIRTH',
 'CITY_OF_BIRTH',
 'NACIONALITY',
 'RESIDENCIAL_STATE',
 'RESIDENCIAL_CITY',
 'RESIDENCIAL_BOROUGH',
 'FLAG_RESIDENCIAL_PHONE',
 'RESIDENCIAL_PHONE_AREA_CODE',
 'RESIDENCE_TYPE',
 'MONTHS_IN_RESIDENCE',
 'FLAG_MOBILE_PHONE',
 'FLAG_EMAIL',
 'PERSONAL_MONTHLY_INCOME',
 'OTHER_INCOMES',
 'FLAG_VISA',
 'FLAG_MASTERCARD',
 'FLAG_DINERS',
 'FLAG_AMERICAN_EXPRESS',
 'FLAG_OTHER_CARDS',
 'QUANT_BANKING_ACCOUNTS',
 'QUANT_SPECIAL_BANKING_ACCOUNTS',
 'PERSONAL_ASSETS_VALUE',
 'QUANT_CARS',
 'COMPANY',
 'PROFESSIONAL_STATE',
 'PROFESSIONAL_CITY',
 'PROFESSIONAL_BOROUGH',
 'FLAG_PROFESSIONAL_PHONE',
 'PROFESSIONAL_PHONE_AREA_CODE',
 'MONTHS_IN_THE_JOB',
 'PROFESSION_CODE',
 'OCCUPATION_TYPE',
 'MATE_PROFESSION_CODE',
 'EDUCATION_LEVEL.1',
 'FLAG_HOME_ADDRESS_DOCUMENT',
 'FLAG_RG',
 'FLAG_CPF',
 'FLAG_INCOME_PROOF',
 'PRODUCT',
 'FLAG_ACSP_RECORD',
 'AGE',
 'RESIDENCIAL_ZIP_3',
 'PROFESSIONAL_ZIP_3',
 'TARGET_LABEL_BAD=1']

In [6]:
vars = [
 'QUANT_DEPENDANTS',
 'MONTHS_IN_RESIDENCE',
 'FLAG_MOBILE_PHONE',
 'FLAG_EMAIL',
 'PERSONAL_MONTHLY_INCOME',
 'OTHER_INCOMES',
 'FLAG_VISA',
 'FLAG_MASTERCARD',
 'FLAG_DINERS',
 'FLAG_AMERICAN_EXPRESS',
 'FLAG_OTHER_CARDS',
 'QUANT_BANKING_ACCOUNTS',
 'QUANT_SPECIAL_BANKING_ACCOUNTS',
 'PERSONAL_ASSETS_VALUE',
 'QUANT_CARS',
 'MONTHS_IN_THE_JOB',
 'PROFESSION_CODE',
 'OCCUPATION_TYPE',
 'FLAG_CPF',
 'FLAG_INCOME_PROOF',
 'TARGET_LABEL_BAD=1']

gdf = df.loc[ :, vars ]

In [18]:
X.describe()

,QUANT_DEPENDANTS,MONTHS_IN_RESIDENCE,FLAG_EMAIL,PERSONAL_MONTHLY_INCOME,OTHER_INCOMES,FLAG_VISA,FLAG_MASTERCARD,FLAG_DINERS,FLAG_AMERICAN_EXPRESS,FLAG_OTHER_CARDS,QUANT_BANKING_ACCOUNTS,QUANT_SPECIAL_BANKING_ACCOUNTS,PERSONAL_ASSETS_VALUE,QUANT_CARS,MONTHS_IN_THE_JOB,PROFESSION_CODE,OCCUPATION_TYPE,FLAG_CPF,FLAG_INCOME_PROOF
count,39170.000000,39170.000000,39170.000000,39170.000000,39170.000000,39170.000000,39170.000000,39170.000000,39170.000000,39170.000000,39170.000000,39170.000000,3.917000e+04,39170.000000,39170.000000,39170.000000,39170.000000,39170.0,39170.0
mean,0.685754,9.527368,0.747613,919.939174,40.036305,0.120347,0.105029,0.001200,0.001838,0.002298,0.437912,0.437912,2.181768e+03,0.428159,0.009931,7.989175,2.473858,0.0,0.0
std,1.213641,10.636813,0.434388,8671.564052,1005.008805,0.325371,0.306595,0.034619,0.042835,0.047880,0.496856,0.496856,1.631669e+04,0.494818,0.411393,3.264285,1.532942,0.0,0.0
min,0.000000,0.000000,0.000000,60.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.0,0.0
25%,0.000000,1.000000,0.000000,363.515000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,9.000000,1.000000,0.0,0.0
50%,0.000000,5.000000,1.000000,500.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,9.000000,2.000000,0.0,0.0
75%,1.000000,15.000000,1.000000,800.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000e+00,1.000000,0.000000,9.000000,4.000000,0.0,0.0
max,53.000000,228.000000,1.000000,959000.000000,194344.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.800000e+06,1.000000,35.000000,18.000000,5.000000,0.0,0.0

In [17]:
y = gdf['TARGET_LABEL_BAD=1']
X = gdf.drop( ['FLAG_MOBILE_PHONE','TARGET_LABEL_BAD=1'], axis=1)

def maxmin(z):
  u = (z-min(z))/(max(z)-min(z))
  return u

U = X.apply(maxmin)

from sklearn.linear_model import LogisticRegression

reg = LogisticRegression(penalty=None)
reg = reg.fit(U,y)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [15]:
gdf.head()

,QUANT_DEPENDANTS,MONTHS_IN_RESIDENCE,FLAG_MOBILE_PHONE,FLAG_EMAIL,PERSONAL_MONTHLY_INCOME,OTHER_INCOMES,FLAG_VISA,FLAG_MASTERCARD,FLAG_DINERS,FLAG_AMERICAN_EXPRESS,...,QUANT_BANKING_ACCOUNTS,QUANT_SPECIAL_BANKING_ACCOUNTS,PERSONAL_ASSETS_VALUE,QUANT_CARS,MONTHS_IN_THE_JOB,PROFESSION_CODE,OCCUPATION_TYPE,FLAG_CPF,FLAG_INCOME_PROOF,TARGET_LABEL_BAD=1
0,1,15.0,N,1,900.0,0.0,1,1,0,0,...,0,0,0.0,0,0,9.0,4.0,0,0,1
1,0,1.0,N,1,750.0,0.0,0,0,0,0,...,0,0,0.0,0,0,11.0,4.0,0,0,1
4,0,12.0,N,1,1200.0,0.0,0,0,0,0,...,0,0,0.0,0,0,9.0,5.0,0,0,1
5,0,4.0,N,1,500.0,0.0,0,0,0,0,...,1,1,0.0,1,0,9.0,2.0,0,0,1
6,2,1.0,N,1,320.0,0.0,0,0,0,0,...,0,0,0.0,0,0,11.0,4.0,0,0,1